#!/usr/bin/env python

import sys
import cPickle
import gastrometry

def parse_args():
    """Handle the command line arguments to gastrogp executable.

    Returns the args as an argparse.Namespace object.

    It will have the following fields:

    args.config_file
    args.verbose
    args.log_file
    args.version
    """
    import argparse

    description = "Run Gaussian Processes on astrometry residuals.\n"
    description += "See https://github.com/PFLeget/gastrometry for documentation."

    parser = argparse.ArgumentParser(description=description, add_help=True)
    parser.add_argument(
            'config_file', type=str, nargs='?',
            help='the configuration file')

    args = parser.parse_args()

    if args.config_file == None:
        if args.version:
            print(version_str)
        else:
            parser.print_help()
        sys.exit()

    return args

def main():
    args = parse_args()
    # Read the config file
    config = gastrometry.read_config(args.config_file)
    # Run the gastrify function
    gastrometry.gastrify(config)

if __name__ == '__main__':
    main()
